### ISSUE TITLE
PopUp and modals positioning is off

### ISSUE THREAD

**Issue by Issiedoesit** [unstructuredstudio/zubhub#606] opened 2023-03-08 22:00 UTC
**Describe the bug**
The notifications popup is positioned such that it slides beneath the navbar while open and hides some of the content on mobile devices

**To Reproduce**

1. Go to the website
2. Click on mobile menu hamburger and select notifications
3. Scroll down up and down
4. The popup is not properly positioned and slides beneath the navbar cutting off some of the content

**Expected behavior**
All popup should be properly positioned and height of the navbar should be considered on mobile while positioning them.

**Screenshots**
![80317B8C-1C4E-40B9-8D7D-73B91073B859](https://user-images.githubusercontent.com/105283590/223859953-e4af8ab7-f66f-453a-be08-3c883f94ad01.png)

https://user-images.githubusercontent.com/105283590/223860205-71189f20-7cd6-426d-a880-a480e0515321.MOV

The issue can be assigned to me .

**Comment by srish** [comment] 2023-09-04 20:50
Closing this as a duplicate of #732

**Closed as completed by srish** 2023-09-04 20:50 UTC
