### ISSUE TITLE
Fix padding around creators page for users who don't have an account

### ISSUE THREAD

**Issue by Mbeute23** [unstructuredstudio/zubhub#956] opened 2023-10-25 13:56 UTC
**Describe the bug**
The spacing around the screen frame is too tight so the element don't breath 

**To Reproduce**

1. Go to 'Zubhub website'
2. Click on 'the dropdown and select creators then search for any creator name'
3. See error

**Expected behavior**
They should increase the padding around the screen. 
They should have a fixed width in which the content can fit in.

**Screenshots**

<img width="1359" alt="Screen Shot 2023-10-25 at 2 16 07 PM" src="https://github.com/unstructuredstudio/zubhub/assets/146943654/ab1e78ec-210f-4135-a86e-bf47fc5a5bd8">

**Comment by CodebyCc** [comment] 2023-10-27 18:57
can i be assigned to this issue Please?

**Comment by aqsaaqeel** [comment] 2023-11-06 19:21
Hey @Mbeute23 I am not able to reproduce this bug on my end, could you elaborate?

**Comment by srish** [comment] 2023-11-10 18:30
This would be addressed as part of larger project improvements

**Closed as completed by srish** 2023-11-10 18:30 UTC
