### ISSUE TITLE
Case sensitivity of text causes duplication of "Materials used" and "Hashtags" when creating a project

### ISSUE THREAD

**Issue by d-arkangel** [unstructuredstudio/zubhub#978] opened 2023-10-27 22:40 UTC
**Describe the bug**
On the section that requires you to select materials used when creating a project, duplication of materials occur. This happens even when the material used is being typed out or selected from the options available.

**To Reproduce**

1. Create project
2. When adding materials used and hashtags, this happens:

https://github.com/unstructuredstudio/zubhub/assets/146884658/3a80b5b9-d078-48bd-af96-e5019bdc4760

 and this too:

https://github.com/unstructuredstudio/zubhub/assets/146884658/5799de35-0089-44e1-a5e9-db85f2134432

As can be seen from the videos above, typing in a hashtag or material used when CAPS LOCK is on causes a duplication of materials, even when selected from the dropdown options.

**Expected behavior**
Only one display per item (hashtag or material used) should be allowed to be added to a project. Maybe if case sensitivity is turned off for these sections, it will not allow for duplicity.

A developer should be able to take this case, I think. @srish @tuxology, I hope this is fine, and I hope you're both fine too. Speedy recovery wishes.

**Comment by srish** [comment] 2023-10-30 22:32
Closing as a duplicate of another task #776

**Closed as completed by srish** 2023-10-30 22:32 UTC

**Comment by d-arkangel** [comment] 2023-10-31 08:02
Oh, my apologies. It was an oversight. I went through the issues and didn't note that. Thank you, @srish
