### ISSUE TITLE
Location Select option field

### ISSUE THREAD

**Issue by EbukaOkoye** [unstructuredstudio/zubhub#598] opened 2023-03-08 13:39 UTC
@srish 

I noticed that the location field in the sign up page which is a select dropdown option has "none" as its only option.

I want to suggest to change the location dropdown option to an input field where the user can input their addresses when signing up

**Comment by Dejipot** [comment] 2023-03-08 14:31
Will like to work on this project too once approved

**Comment by tuxology** [comment] 2023-03-08 20:11
Can't reproduce this in any of our hosted hubs. We've seen this being reported earlier #405 but was closed because it was an issue with the local setup while developing. Closing this as well

**Closed as completed by tuxology** 2023-03-08 20:11 UTC

**Comment by fiddyhamma** [comment] 2023-10-03 15:45
hello @tuxology 
Although this has been closed, i am currently facing the same issue with both a desktop and mobile device, also the sign up button is blank and not responsive. What do you suggest as i can't create an account at the moment
