### ISSUE TITLE
breadCrumb navigator function getting displayed

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#632] opened 2023-03-10 18:09 UTC
## The Bug
The function for `breadCrub.link.staff-picks` get displayed when clicked on view all projects
It shouldn't be display and it is acting like a link in the website.

## To Reproduce

- Visit [Zubhub](https://zubhub.unstructured.studio/)
- Click on `view all`

## Expected behavior

Either nothing or `Staff Pick` needs to be displayed there.

## Screenshots

![image](https://user-images.githubusercontent.com/93364240/224391431-32386629-1cab-4898-9b1d-2f7d72d9e37f.png)

**Comment by psalmuelle** [comment] 2023-03-10 20:34
#619 also raised the same issue!

**Comment by tuxology** [comment] 2023-03-10 21:20
Closing this as duplicate of #619

**Closed as completed by tuxology** 2023-03-10 21:20 UTC
