### ISSUE TITLE
Bug: Responsiveness not working well for some devices

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#860] opened 2023-10-10 23:37 UTC
**Describe the bug**
In terms of user experience(UX), the responsiveness of  a website is basically a point to be focusing on. On going through the Zubhub website, I was able to identify some issues with responsiveness for devices like **iPhone 12, iPhone XR, Samsung Galaxy 8**

**To Reproduce**

1. Go to the Zubhub platform
2. Switch between devices
3. Refresh to load the styling for that device size

**Expected behavior**
A normal or expected behavior will be the good responsiveness of the platform. A screenshot will be found lower in this issue

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/d03bf14c-d2ef-4eff-9f88-ccaa1e4d6974)

**Comment by srish** [comment] 2023-10-10 23:50
Umbrella task is here, where you can contribute more: https://github.com/unstructuredstudio/zubhub/issues/823. Closing this as a duplicate of 823.

**Closed as completed by srish** 2023-10-10 23:50 UTC

**Comment by yokwejuste** [comment] 2023-10-11 00:04
sure sure
