### ISSUE TITLE
All category options (except 'None') are missing from the dropdown

### ISSUE THREAD

**Issue by srish** [unstructuredstudio/zubhub#474] opened 2022-05-13 01:11 UTC
In the project creation form, we used to show a bunch of categories from here: https://github.com/unstructuredstudio/zubhub/blob/master/zubhub_backend/zubhub/projects/management/commands/categories.txt for the question "What is the category of your project?". Now these options are gone, and we only see "None" as an option in the dropdown.

**Comment by NdibeRaymond** [comment] 2022-05-14 03:04
closing because we were unable to reproduce this

**Closed as completed by NdibeRaymond** 2022-05-14 03:04 UTC
Labels: bug, good first issue, high priority
