### ISSUE TITLE
Project creation does not show validation for adding image

### ISSUE THREAD

**Issue by aqsaaqeel** [unstructuredstudio/zubhub#995] opened 2023-11-09 11:43 UTC
**Describe the bug**
Adding an image/video is necessary for creating a project. Currently, there is no validation for adding an image while creating a project. The user can mistakenly skip adding an image and it will result in a project not being created but the user will have no way of knowing what went wrong. 

**To Reproduce**

1. Go to '[Create Project](https://zubhub.unstructured.studio/projects/create)'
2. Create project without adding any image
3. You will see that you are unable to create the project.

**Expected behavior**
The user must get a validation error of not having added an image if they try to go to step 3 without adding an image.

**Solution**
1. We give a validation error when a user tries to go to the next step without an image.
2. Disable the next button until the user uploads an image.

**Recording showing the whole issue**

https://github.com/unstructuredstudio/zubhub/assets/85514520/6965a57d-801e-47b2-a200-5c1aeae2bc3a

**Comment by srish** [comment] 2023-11-10 18:15
This is a duplicate of #340

**Closed as completed by srish** 2023-11-10 18:15 UTC

**Comment by aqsaaqeel** [comment] 2023-11-13 20:31
@srish #340 only talks about image validation when size is greater 2MB which is an occasional situation but currently the image has no validation for any size of image. We should increase the scope of #340 or create a separate issue for that.
