### ISSUE TITLE
Fix buttons on mobile

### ISSUE THREAD

**Issue by mehreeee** [unstructuredstudio/zubhub#958] opened 2023-10-25 17:12 UTC
**Describe the bug**
On mobile devices, some of the buttons are mismatched and not uniform

**Screenshots**
![9DCED574-D301-497E-8298-3527E214CB57](https://github.com/unstructuredstudio/zubhub/assets/105458062/44deb457-4896-4090-b0b3-bfdfa41ff65e)

![0E6ED613-D60F-452F-8812-3A9E9D506394](https://github.com/unstructuredstudio/zubhub/assets/105458062/fc000e29-4851-4d25-83cb-8cbbff92171b)

![F1C6D7AF-D4C8-4230-94A8-F73F353CD367](https://github.com/unstructuredstudio/zubhub/assets/105458062/449a7f90-1bf2-41e8-a336-7ec1b00eff61)

**Comment by ladyami** [comment] 2023-10-25 19:21
@mehreeee good job
@srish Consider creating a dedicated GitHub issue for reporting minor UI bugs. This will allow contributors to easily submit their findings as comments on the issue. By acknowledging these reports with a "like" or similar action, you can provide contributors with an acceptance to record their contributions. Given the numerous issues already opened for mobile responsiveness, consolidating new reports under a single issue will streamline the process.

**Comment by DonPresh** [comment] 2023-10-25 19:41
@ladyami This will help a lot.
I also think that maybe creating a new or updating the existing design system will help solve most of these issues and maintain consistency across board.
@mehreeee What do you think?

**Comment by mehreeee** [comment] 2023-10-25 19:49
> @ladyami This will help a lot.
> I also think that maybe creating a new or updating the existing design system will help solve most of these issues and maintain consistency across board.
> @mehreeee What do you think?

Yeah I agree, most of the inconsistencies across the designs is because there’s no solid design system/style guide for reference.

**Comment by ladyami** [comment] 2023-10-25 19:53
@DonPresh @mehreeee that is just the solution

**Comment by Boluwatifey1** [comment] 2023-10-26 05:50
> @ladyami This will help a lot. I also think that maybe creating a new or updating the existing design system will help solve most of these issues and maintain consistency across board. @mehreeee What do you think?

I also agree with that, there are lots of design needs to be updated

**Comment by srish** [comment] 2023-10-30 22:59
Nice suggestions but closing as a duplicate of https://github.com/unstructuredstudio/zubhub/issues/823

**Closed as completed by srish** 2023-10-30 22:59 UTC
