### ISSUE TITLE
Login section not visually balanced

### ISSUE THREAD

**Issue by Aishatt** [unstructuredstudio/zubhub#768] opened 2023-10-03 21:22 UTC
**Login page is not visually balanced**
The login page looks visually imbalanced as a result of the fixed navbar on-scroll effect, the white space between the main and footer sections is also contributing to this issue  Also, in the footer section, the text is not visible on the white background.
As seen in the image attached below.

**To reproduce**
1.  Go to '[the ZubHub website](hhttps://zubhub.unstructured.studio/login)'
2. Scroll to the bottom (footer) and hover around the footer

**Expected behavior**
The Login page is expected to be visually balanced, the fixed navbar effect should be removed, which will make the login section vertically balanced. Reduce the margin between the main and footer sections and make this section. The footer text should be visible/readable. I would also like to suggest making the footer a bit distinctive by not using a white background color
<img width="1440" alt="Screenshot 2023-10-03 at 21 16 47" src="https://github.com/unstructuredstudio/zubhub/assets/82312567/1834f524-b3b5-4598-89a5-74b8d32b583e">

@srish @tuxology Can I work on fixing these issues?

**Comment by srish** [comment] 2023-10-03 21:39
Closing as a duplicate of #742

**Closed as completed by srish** 2023-10-03 21:39 UTC
