### ISSUE TITLE
Draft projects should not show up in the search bar for user who created it

### ISSUE THREAD

**Issue by darechan** [unstructuredstudio/zubhub#581] opened 2023-03-07 08:47 UTC
## The Bug
Projects created in draft mode by a user show up in search results for them on the landing page through the search bar

## To Reproduce

- Visit https://zubhub.unstructured.studio/
- Login
- Create a project in draft mode
- Go back to the home screen
- Search for the project you created
- It shows up in the results

## Expected behavior
Draft projects should not show up in the search results

**Comment by darechan** [comment] 2023-03-07 08:53
@tuxology @srish Hey! Please take a look at this issue. I'd love to be assigned to this issue if possible!

**Comment by khallow7** [comment] 2023-03-07 10:59
Yes, I found these issues as well. Plus, other things are not behaving the way they should. .

When I set the project to the “only me” option, the project is still visible to “authenticated users” → The project should only be seen by me, or it should move to drafts.

When I set the project to “only a few Zubhub users” it sends the project to draft, and it's only visible to me. → The project should be visible to authenticated users that you can select.

When I try to set “for all registered Zubhub users” then an additional field opens to input usernames. → The project should be visible to all the registered/authenticated users.

The labels names are not rightly ordered. These need to be fixed.

More details here:
https://github.com/unstructuredstudio/zubhub/issues/556#issuecomment-1457955782

**Comment by tuxology** [comment] 2023-03-07 22:51
@darechan Assigned to you. The correct behavior is what @khallow7  suggests. Note that the ZubHub hosted on https://zubhub.unstructured.studio is in Public mode. ON your local install you can check mode using Django Admin interface. Check the behavior of these project modes according to what @khallow7 suggests and verify if it works correctly with Public mode Zubhub as well. The issue most probably lies there, i.e. the behavior of various project viewing modes is not defined correctly in public mode Zubhub. 

⚠️ Note: @darechan Please follow discussion on #556 closely. This issue not about UX, it is about functionality of viewing modes - specifically **draft projects of other users ending up on authenticated users view** Only of this condition is met, attempt to fix this!!

**Comment by tuxology** [comment] 2023-03-07 22:51
@khallow7 Can you file a separate issue regarding the correct ordering of "only few zubhub users" and "for all registered users" int he list? That is a valid bug

**Comment by khallow7** [comment] 2023-03-08 04:55
> 

Will do that.

**Comment by iykat** [comment] 2023-09-30 16:25
> 

@tuxology @srish the title of the issue is a bit confusing. 

the title says draft projects should not appear in a search result for the user who created them. however, @tuxology's comment here ("draft projects of other users ending up on authenticated users view") indicates it's only a problem when it appears for other users, and in that instance alone one should attempt to fix the problem.

These are two completely different issues in my understanding. can you kindly provide some clarity?

**Comment by iykat** [comment] 2023-09-30 16:28
I attempted to reproduce the issue by creating two different accounts.  I realized that draft projects do indeed appear for the user who created them but do not appear for other users.

**Comment by srish** [comment] 2023-10-02 23:03
@iykat You can ignore @tuxology's comment as that issue got fixed earlier. The problem right now is exactly what is in the issue title: draft projects appear in a search result for the user who created them and they shouldn't.

**Comment by benndip** [comment] 2023-10-03 03:21
Hello @srish , could I be assigned this issue? I have already solved it, and it works, I just want to be assigned so that I can open a PR for it ASAP.

Thanks!

**Comment by yokwejuste** [comment] 2023-10-03 19:42
@srish found out what happened and will like to work on this and fix it

**Comment by benndip** [comment] 2023-10-03 21:37
Hello @tuxology , please can you assign this issue to me so that I can make a PR for it? I have already solved it locally on my computer

**Comment by benndip** [comment] 2023-10-04 05:06
@srish @tuxology  I just open a PR [https://github.com/unstructuredstudio/zubhub/pull/775](url) that fixes this issue

**Closed as completed** 2023-10-04 21:06 UTC
Labels: bug, good first issue, low priority
