### ISSUE TITLE
Overlapping of  signIn form and inconsistent padding between form and navbar

### ISSUE THREAD

**Issue by Formasitchijoh** [unstructuredstudio/zubhub#729] opened 2023-09-02 16:52 UTC
Recently on the new design of the zubhub web page theres is an overlapping of the signIn form when the user loads the form twice, also there is no padding between the navbar and the onboarding page  or the notification page

## To Reproduce
1. Try loging into your account by clicking the user profile 
2. Select sign In and let the page loads
3. when the page loads click on the profile again the signUp/SignIn popup overlaps on the previous page
 This behaviour is inconsistent and might not be appealing to most users

### Expected behavior
The loaded signIn form should close when the user clicks the user profile image so that the user can make a different choice or stick with the previous one

Here is a snippet of the error

https://github.com/unstructuredstudio/zubhub/assets/76694292/20683bf0-e6bc-42ea-a277-1fafb17efc7e

**Comment by srish** [comment] 2023-09-05 00:26
Closing as a duplicate of #732

**Closed as completed by srish** 2023-09-05 00:26 UTC

**Comment by Formasitchijoh** [comment] 2023-09-05 10:31
Ohh sorry I didn't notice I'll check it out and review it
