### ISSUE TITLE
Feature - User not receiving a verification link for their email

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#810] opened 2023-10-06 05:46 UTC
**Describe the feature request**
In normal scenario users should be registering to the platform and be able to receive a link or any other suitable verification method so they can validate the exitance of their emails and or phone number

![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/9aa66b82-c07e-43d7-86a2-ff958ade3186)

**Comment by coderatomy** [comment] 2023-10-06 13:36
I think this is also related to #811 @yokwejuste. To anyone interested in this. This is a known issue. Checkout what @tuxology commented at #661

**Comment by yokwejuste** [comment] 2023-10-06 13:38
> I think this is also related to #811 @yokwejuste. To anyone interested in this. This is a known issue. Checkout what @tuxology commented at #661 

Got it, I also read what he said saying that we did not yet implemented the twilio/sendgrid email verification

**Comment by srish** [comment] 2023-10-07 00:57
Closing as a duplicate of 661

**Closed as completed by srish** 2023-10-07 00:57 UTC
