### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by pachougu** [unstructuredstudio/zubhub#817] opened 2023-10-06 09:44 UTC
also i noticed that at edit profile, that users/creators can't make any edit on their profile, of which i believe that creators may want to change their or password, so to give then a better UX i'll love to suggest the we give them room for that, also the micro copy on the button at the users profile, is those not look good when it comes to user experience, it will keep making clicking on the button, i can provide a good UX to this issue i been assigned to me 
![Capturete](https://github.com/unstructuredstudio/zubhub/assets/146971182/efee5a35-f43d-442e-8c27-16dec6f247a1)

**Comment by srish** [comment] 2023-10-07 01:10
Closing this as a duplicate of another issue.

**Closed as completed by srish** 2023-10-07 01:10 UTC
