### ISSUE TITLE
Bug: Assertion Error of type None

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#928] opened 2023-10-19 09:10 UTC
**Describe the bug**
Creating a project on Zubhub and coming later to complete can be something regular, but now when you create a project and it get into the drafts when coming back to it to edit you get an Assertion error, due to the video or some assets that were not submitted before.

**To Reproduce**

1. Got to Zubhub
2. Create a project and omit the media (image and video)
3. Leave it likethat, go to somewhere else on the platotform and on coming back and trying to submit, 
4. You see error

**Expected behavior**
An expected behavior will be a scenario in which we come to continue working with no hindrance or bug.

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/668dbe6d-28b5-4d66-9f89-f0ceee0c23be)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/1d8b69e3-fcd3-46f6-9c88-baf8705fe68f)

**Comment by srish** [comment] 2023-10-20 19:49
A possible duplicate of https://github.com/unstructuredstudio/zubhub/issues/340

**Closed as completed** 2023-10-20 19:49 UTC
