### ISSUE TITLE
Breadcrumb not working well after the `view all` button is clicked on the home page

### ISSUE THREAD

**Issue by KramStyles** [unstructuredstudio/zubhub#645] opened 2023-03-11 15:03 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/21022645/224491602-61754042-9a84-4cf3-8e09-a939457e1e0f.png)

When a user visits the home page and clicks on the `view all` button just below the hero section, it takes them to another page. This page has a breadcrumb that isn't working well. I believe that the term `breadcrumb.link.staff-pick` shouldn't be there. 

![image](https://user-images.githubusercontent.com/21022645/224491687-68cbca51-df73-48e7-91f3-6c8c3cbc1265.png)
Also this breadcrumb is a link and when you click on it, it takes you to another page with a failed `delete` report. I believe this shouldn't be the case
![image](https://user-images.githubusercontent.com/21022645/224491782-a902e5db-943c-40a2-88a4-ab24e5b2b5ae.png)

**Comment by KramStyles** [comment] 2023-03-11 15:03
@tuxology can I please try to fix this?

**Comment by darechan** [comment] 2023-03-11 16:38
Duplicate of #619

**Closed as completed** 2023-03-11 17:50 UTC
