### ISSUE TITLE
Bug: Password Reset not receiving emails

### ISSUE THREAD

**Issue by yokwejuste** [unstructuredstudio/zubhub#811] opened 2023-10-06 05:53 UTC
**Describe the bug**
On trying to reset a password a user who submits his email for reset will not receiving the email for the reset.

**To Reproduce**

1. Go to the password reset option on the website: [reset password](https://zubhub.unstructured.studio/password-reset)
2. Submit the form and never receive the email

**Expected behavior**
In normal circumstances we are to receive the email and on clicking we are to have the reset screen displayed taking the new password.

**Screenshots**
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/7ed048dd-e55a-4576-a9f0-9ce4e2600f85)
![image](https://github.com/unstructuredstudio/zubhub/assets/71908316/272880ee-d7ba-4c2f-8658-6ecb1d7d0ac9)

**Comment by N-TITIAN** [comment] 2023-10-06 08:01
@yokwejuste I noticed that too, didn't receive any email , can work on the ux of the reset screen?

**Comment by coderatomy** [comment] 2023-10-06 09:57
Hey @yokwejuste  and @N-TITIAN, this is related to #661 
Note where @tuxology  said:

 We currently do have email sending features implemented via Sendgrid but the verification feature does not exist. We 
 have not implemented it yet to reduce friction of creating new accounts initially. The current model we have is same as 
what reddit has, which allows users to remain anonymous to an extent. We can keep this open and revisit this I think.

**Comment by yokwejuste** [comment] 2023-10-06 13:09
Ohh I see that now , thanks

**Comment by srish** [comment] 2023-10-07 00:58
Closing as a duplicate of another issue

**Closed as completed by srish** 2023-10-07 00:58 UTC
