### ISSUE TITLE
Create project page is blank

### ISSUE THREAD

**Issue by JulietMadu** [unstructuredstudio/zubhub#774] opened 2023-10-04 00:30 UTC
When you switch to creator mode and try to create project, it brings out a blank page.

check link here:
https://zubhub.unstructured.studio/projects/create

![Screenshot (204)](https://github.com/unstructuredstudio/zubhub/assets/128796937/c14bacbd-1643-41c3-a6e7-eb5cef16cd52)

**Comment by aqsaaqeel** [comment] 2023-10-04 00:32
Seems to be working fine for me, can you tell me the steps to reproduce this issue?
![Screenshot from 2023-10-04 06-01-11](https://github.com/unstructuredstudio/zubhub/assets/85514520/5e56a3c8-16e1-4686-8b8d-057f2ff79352)

**Comment by JulietMadu** [comment] 2023-10-04 00:51
> Seems to be working fine for me, can you tell me the steps to reproduce this issue? ![Screenshot from 2023-10-04 06-01-11](https://user-images.githubusercontent.com/85514520/272430209-5e56a3c8-16e1-4686-8b8d-057f2ff79352.png)

switch to creator mode

**Comment by srish** [comment] 2023-10-04 20:11
May have been caused by recent deployment changes. Closing this one.

**Closed as completed by srish** 2023-10-04 20:11 UTC
