### ISSUE TITLE
Improve arrangement of cards on users' profile page ( Mobile)

### ISSUE THREAD

**Issue by Dumzy006** [unstructuredstudio/zubhub#962] opened 2023-10-25 20:40 UTC
@srish I noticed on mobile, the cards for projects, following and followers in the users' profile page could look better if all cards are placed on a line there by reducing the amount of space occupied. so I came up with a design

See screenshot of current design below
![WhatsApp Image 2023-10-25 at 21 25 39_76aa80cf](https://github.com/unstructuredstudio/zubhub/assets/136137889/e1c76ab9-b34e-4948-a2a0-a124266fb86b)

Below is the design I came up with

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/658f35ee-74ab-4132-8469-de35934a010b)

**Comment by Boluwatifey1** [comment] 2023-10-26 05:35
> @srish I noticed on mobile, the cards for projects, following and followers in the users' profile page could look better if all cards are placed on a line there by reducing the amount of space occupied. so I came up with a design
> 
> See screenshot of current design below ![WhatsApp Image 2023-10-25 at 21 25 39_76aa80cf](https://user-images.githubusercontent.com/136137889/278142210-e1c76ab9-b34e-4948-a2a0-a124266fb86b.jpg)
> 
> Below is the design I came up with
> 
> ![image](https://user-images.githubusercontent.com/136137889/278143134-04faad6e-218e-486f-aec4-b0577b92016b.png)

this is a nice suggestion but is this screen size not bigger that the mobile screen?

**Comment by Dumzy006** [comment] 2023-10-26 05:41
That's a mobile screen (Iphone 13)
Same screen size used in zubhub figma file

**Comment by brrkrmn** [comment] 2023-10-27 07:32
looks good @Dumzy006

**Comment by srish** [comment] 2023-10-30 23:02
Closing as a duplicate of https://github.com/unstructuredstudio/zubhub/issues/823. Enhancements like these will be made as part of a larger project. This issue will be tagged in the other one with this comment so we can remember to incorporate your suggestions when we pick the big project.

**Closed as completed by srish** 2023-10-30 23:02 UTC
