### ISSUE TITLE
Improve the edit and delete button on draft mode ( Mobile)

### ISSUE THREAD

**Issue by Dumzy006** [unstructuredstudio/zubhub#954] opened 2023-10-25 10:52 UTC
Hello @srish I noticed on mobile when I select a particular draft  the Edit and Delete" button is vertically placed and  too close to each other 

Here is a screenshot of how it currently looks.

![WhatsApp Image 2023-10-25 at 11 35 50_e30f0a54](https://github.com/unstructuredstudio/zubhub/assets/136137889/a5419a6c-18d5-46be-aba9-4388ee31337d)

I came up with two suggestions

First suggestion
 I made an improvement on the buttons by providing a kebab menu icon....Once a user clicks on it he sees edit and delete option.. This  saves space and avoid clutter on the mobile interface.

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/1fd3279d-ad87-41a4-a278-a903788cc4a2)

Second suggestion
I placed the buttons horizontally and gave some gap (8) between them

![image](https://github.com/unstructuredstudio/zubhub/assets/136137889/c97904fd-117f-4be2-899a-fee558d42eaa)

What do you think?

**Comment by DonPresh** [comment] 2023-10-25 12:11
@Dumzy006 I'm leaning more into your first suggestion.  Using the meatballs icon improves the UI and leaves more white space. 

For the second suggestion, I think using bold buttons for both edit and delete might overwhelm the user. Maybe make the delete lighter or even an outline.  What do you think?

Great designs Btw.

**Comment by Dumzy006** [comment] 2023-10-25 13:17
Thanks @DonPresh 

I initially considered making the "Delete" button an outlined button, but wanted to make it consistent with what we have on the desktop view. Except we want to consider improving on that

**Comment by DonPresh** [comment] 2023-10-25 13:42
Oh okay. That makes sense.

**Comment by srish** [comment] 2023-10-30 23:03
Closing as a duplicate of https://github.com/unstructuredstudio/zubhub/issues/823. Enhancements like these will be made as part of a larger project. This issue will be tagged in the other one with this comment so we can remember to incorporate your suggestions when we pick the big project.

**Closed as completed by srish** 2023-10-30 23:03 UTC
