### ISSUE TITLE
sign up error message on password 

### ISSUE THREAD

**Issue by pachougu** [unstructuredstudio/zubhub#813] opened 2023-10-06 08:12 UTC
@srish while trying to register on zubhub during the registration process, when i entered my new password the error message i got "all numeric "  i  was confused at first so i thought i should use only numerical numbers but it still did not work, until i used, alphabet, numbers and symbol then it worked, so am thing that we should correct the error copy for the password, better copy write will improve the UX of a product

**Comment by coderatomy** [comment] 2023-10-06 13:32
Hey @pachougu, are you still experiencing this issue? If not, you can close it. Thanks

**Comment by srish** [comment] 2023-10-07 01:02
Cannot reproduce and iterating on the sign-up form's design is on our roadmap.

**Closed as completed by srish** 2023-10-07 01:02 UTC
