### ISSUE TITLE
Label Named incorrectly

### ISSUE THREAD

**Issue by cherish2003** [unstructuredstudio/zubhub#682] opened 2023-03-17 06:48 UTC
**Describe the bug**
Label name is not named correctly
**To Reproduce**
1. Go to [zubhubWebsite](https://zubhub.unstructured.studio/)
2. Click on ViewAll
3. Beside the `Projects` tag you can see the label named incorrectly

**Expected behavior**
Label name should be named appropriately

**Screenshots**
<img width="1440" alt="Screenshot 2023-03-17 at 12 11 36 PM" src="https://user-images.githubusercontent.com/88829894/225832666-0afb4869-b90c-4ddd-9762-376f3c66534d.png">

**Comment by cherish2003** [comment] 2023-03-17 06:49
@srish @tuxology if this issue is approved i would like to work on this

**Comment by darechan** [comment] 2023-03-17 10:51
Duplicate of #619

**Closed as completed** 2023-03-17 11:26 UTC
