### ISSUE TITLE
Landing page still scrolls horizontally

### ISSUE THREAD

**Issue by d-arkangel** [unstructuredstudio/zubhub#932] opened 2023-10-20 09:05 UTC
**Describe the the feature request**
Currently, the landing page has this error where it scrolls horizontally. That should not be given that it is  designed with responsiveness in view. Here is what I mean:

https://github.com/unstructuredstudio/zubhub/assets/146884658/d133acf2-1b85-4c2a-9fe4-630df990c00b

**Proposed Solution**
Horizontal scroll should be disabled on the body frame. This can be done by clipping the contents to the main body frame.

**Comment by brrkrmn** [comment] 2023-10-20 13:50
Hey @d-arkangel, #921 fixes this problem but it is not merged yet

**Comment by srish** [comment] 2023-10-20 19:52
Closing as a duplicate of an earlier task.

**Closed as completed by srish** 2023-10-20 19:52 UTC

**Comment by d-arkangel** [comment] 2023-10-20 22:56
> Hey @d-arkangel, #921 fixes this problem but it is not merged yet

Oh OK. Thank you for notifying me.
